import {defineType, defineField} from 'sanity'

const sourceField = defineField({name: 'source', title: 'Source', type: 'reference', to: [{type: 'source'}], validation: (rule) => rule.required()})

export const schemaTypes = [
  defineType({
    name: 'government', title: 'Government', type: 'document',
    fields: [
      defineField({name: 'name', title: 'Name', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'jurisdiction', title: 'Jurisdiction', type: 'string', initialValue: 'Australia'}),
      defineField({name: 'partyOrCoalition', title: 'Party or coalition', type: 'string'}),
      defineField({name: 'startDate', title: 'Start date', type: 'date'}),
      defineField({name: 'endDate', title: 'End date', type: 'date'}),
    ],
    preview: {select: {title: 'name', subtitle: 'partyOrCoalition'}},
  }),
  defineType({
    name: 'manifesto', title: 'Manifesto', type: 'document',
    fields: [
      defineField({name: 'title', title: 'Title', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'party', title: 'Party', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'electionDate', title: 'Election date', type: 'date'}),
      defineField({name: 'jurisdiction', title: 'Jurisdiction', type: 'string', initialValue: 'Australia'}),
      defineField({name: 'documentUrl', title: 'Document URL', type: 'url'}),
      defineField({name: 'source', title: 'Source', type: 'reference', to: [{type: 'source'}]}),
    ],
    preview: {select: {title: 'title', subtitle: 'party'}},
  }),
  defineType({
    name: 'promise', title: 'Promise', type: 'document',
    fields: [
      defineField({name: 'title', title: 'Promise', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'summary', title: 'Plain-language summary', type: 'text', rows: 3}),
      defineField({name: 'party', title: 'Promising party', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'jurisdiction', title: 'Jurisdiction', type: 'string', initialValue: 'Australia'}),
      defineField({name: 'election', title: 'Election', type: 'string'}),
      defineField({name: 'category', title: 'Category', type: 'string', options: {list: ['Cost of living', 'Climate', 'Health', 'Housing', 'Migration', 'Integrity', 'National security', 'Other']}}),
      defineField({name: 'status', title: 'Current status', type: 'string', options: {list: ['Kept', 'Partially kept', 'In progress', 'Not started', 'Broken', 'Reversed', 'Unverifiable']}, initialValue: 'Unverifiable'}),
      defineField({name: 'confidence', title: 'Confidence', type: 'number', validation: (rule) => rule.min(0).max(1)}),
      defineField({name: 'deadline', title: 'Promised deadline', type: 'date'}),
      defineField({name: 'baseline', title: 'Baseline', type: 'string'}),
      defineField({name: 'target', title: 'Target', type: 'string'}),
      defineField({name: 'measurementRule', title: 'Measurement rule', type: 'text', rows: 3}),
      defineField({name: 'statusReason', title: 'Reason for status', type: 'text', rows: 3}),
      defineField({name: 'blockers', title: 'Reported blockers or reasons', type: 'array', of: [{type: 'string'}]}),
      defineField({name: 'manifesto', title: 'Manifesto', type: 'reference', to: [{type: 'manifesto'}]}),
      defineField({name: 'government', title: 'Government', type: 'reference', to: [{type: 'government'}]}),
      defineField({name: 'evidence', title: 'Evidence', type: 'array', of: [{type: 'reference', to: [{type: 'evidence'}]}]}),
      defineField({name: 'milestones', title: 'Milestones', type: 'array', of: [{type: 'reference', to: [{type: 'milestone'}]}]}),
      defineField({name: 'indicators', title: 'Outcome indicators', type: 'array', of: [{type: 'reference', to: [{type: 'indicator'}]}]}),
      defineField({name: 'assessments', title: 'Independent assessments', type: 'array', of: [{type: 'reference', to: [{type: 'assessment'}]}]}),
    ],
    preview: {select: {title: 'title', subtitle: 'status'}},
  }),
  defineType({
    name: 'source', title: 'Source', type: 'document',
    fields: [
      defineField({name: 'title', title: 'Title', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'publisher', title: 'Publisher', type: 'string'}),
      defineField({name: 'url', title: 'URL', type: 'url', validation: (rule) => rule.required()}),
      defineField({name: 'publishedAt', title: 'Published at', type: 'date'}),
      defineField({name: 'sourceType', title: 'Source type', type: 'string', options: {list: ['Manifesto', 'Budget', 'Legislation', 'Parliamentary record', 'Official report', 'Audit', 'Court or regulator', 'Dataset', 'Statistical release', 'Independent assessment', 'Media report']}}),
      defineField({name: 'jurisdiction', title: 'Jurisdiction', type: 'string', initialValue: 'Australia'}),
      defineField({name: 'methodology', title: 'Methodology or coverage', type: 'text', rows: 3}),
      defineField({name: 'notes', title: 'Notes', type: 'text', rows: 3}),
    ],
    preview: {select: {title: 'title', subtitle: 'publisher'}},
  }),
  defineType({
    name: 'evidence', title: 'Evidence', type: 'document',
    fields: [
      defineField({name: 'title', title: 'Evidence title', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'finding', title: 'Finding', type: 'text', rows: 4, validation: (rule) => rule.required()}),
      defineField({name: 'observedAt', title: 'Observed at', type: 'date'}),
      defineField({name: 'effect', title: 'Effect on promise', type: 'string', options: {list: ['Supports', 'Partially supports', 'Contradicts', 'Neutral']}, initialValue: 'Neutral'}),
      defineField({name: 'claimType', title: 'Claim type', type: 'string', options: {list: ['Implementation', 'Output', 'Outcome', 'Reason', 'Contradiction', 'Context']}}),
      defineField({name: 'confidence', title: 'Confidence', type: 'number', validation: (rule) => rule.min(0).max(1)}),
      sourceField,
      defineField({name: 'relatedPromise', title: 'Related promise', type: 'reference', to: [{type: 'promise'}]}),
    ],
    preview: {select: {title: 'title', subtitle: 'effect'}},
  }),
  defineType({
    name: 'milestone', title: 'Milestone', type: 'document',
    fields: [
      defineField({name: 'title', title: 'Milestone', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'description', title: 'Description', type: 'text', rows: 3}),
      defineField({name: 'date', title: 'Date', type: 'date'}),
      defineField({name: 'status', title: 'Status', type: 'string', options: {list: ['Announced', 'Funded', 'Legislated', 'Started', 'Delivered', 'Delayed', 'Cancelled', 'Unclear']}}),
      defineField({name: 'promise', title: 'Promise', type: 'reference', to: [{type: 'promise'}], validation: (rule) => rule.required()}),
      sourceField,
    ],
    preview: {select: {title: 'title', subtitle: 'status'}},
  }),
  defineType({
    name: 'indicator', title: 'Outcome indicator', type: 'document',
    fields: [
      defineField({name: 'title', title: 'Indicator', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'definition', title: 'Definition', type: 'text', rows: 3}),
      defineField({name: 'value', title: 'Observed value', type: 'string'}),
      defineField({name: 'unit', title: 'Unit', type: 'string'}),
      defineField({name: 'period', title: 'Measurement period', type: 'string'}),
      defineField({name: 'direction', title: 'Direction against target', type: 'string', options: {list: ['Improved', 'Worsened', 'Mixed', 'No clear change', 'Not comparable']}}),
      defineField({name: 'promise', title: 'Promise', type: 'reference', to: [{type: 'promise'}], validation: (rule) => rule.required()}),
      sourceField,
    ],
    preview: {select: {title: 'title', subtitle: 'value'}},
  }),
  defineType({
    name: 'assessment', title: 'Independent assessment', type: 'document',
    fields: [
      defineField({name: 'title', title: 'Assessment', type: 'string', validation: (rule) => rule.required()}),
      defineField({name: 'verdict', title: 'Verdict', type: 'string', options: {list: ['Kept', 'Partially kept', 'In progress', 'Not started', 'Broken', 'Reversed', 'Unverifiable']}}),
      defineField({name: 'reasoning', title: 'Reasoning', type: 'text', rows: 5}),
      defineField({name: 'assessor', title: 'Assessor', type: 'string'}),
      defineField({name: 'publishedAt', title: 'Published at', type: 'date'}),
      defineField({name: 'promise', title: 'Promise', type: 'reference', to: [{type: 'promise'}], validation: (rule) => rule.required()}),
      sourceField,
    ],
    preview: {select: {title: 'title', subtitle: 'verdict'}},
  }),
  defineType({
    name: 'claim', title: 'Competing claim', type: 'document',
    fields: [
      defineField({name: 'statement', title: 'Statement', type: 'text', rows: 4, validation: (rule) => rule.required()}),
      defineField({name: 'claimant', title: 'Claimant', type: 'string'}),
      defineField({name: 'claimType', title: 'Claim type', type: 'string', options: {list: ['Government explanation', 'Opposition claim', 'Independent finding', 'Public data interpretation', 'Correction']}}),
      defineField({name: 'confidence', title: 'Confidence', type: 'number', validation: (rule) => rule.min(0).max(1)}),
      defineField({name: 'promise', title: 'Promise', type: 'reference', to: [{type: 'promise'}]}),
      sourceField,
    ],
    preview: {select: {title: 'statement', subtitle: 'claimant'}},
  }),
]
